Presentation/Controllers/AutorController.cs
using Application.AppServices;
using Application.ViewModels;
using NonFactors.Mvc.Grid;

namespace Presentation.Controllers
{
    public class AutorController : GridController<AutorViewModel>
    {
        public AutorController(
            IAutorAppService autorAppService)
            : base(autorAppService)
        {
        }

        protected override void ConfigureGridColumns(IGrid<AutorViewModel> grid)
        {
            grid.Columns.Add(model => model.Nome);
            grid.Columns.Add(model => model.UltimoNome);
            grid.Columns.Add(model => model.Nacionalidade);
            grid.Columns.Add(model => model.Nascimento);
        }
    }
}

Presentation/Controllers/LivroController.cs
using System.Threading.Tasks;
using Application.AppServices;
using Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NonFactors.Mvc.Grid;

namespace Presentation.Controllers
{
    public class LivroController : GridController<LivroViewModel>
    {
        private readonly ILivroAppService _livroAppService;
        private readonly IAutorAppService _autorAppService;

        public LivroController(
            ILivroAppService livroAppService,
            IAutorAppService autorAppService)
            : base (livroAppService)
        {
            _livroAppService = livroAppService;
            _autorAppService = autorAppService;
        }

        // POST: Livro/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public override async Task<IActionResult> Create(LivroViewModel livroViewModel)
        {
            if (!ModelState.IsValid)
            {
                await PreencherSelect(livroViewModel.AutorId);
            }

            return await base.Create(livroViewModel);
        }

        protected override async Task PreencherSelect(int? autorId = null)
        {
            var autores = await _autorAppService.GetAllAsync();

            ViewBag.Autores = new SelectList(
                autores,
                nameof(AutorViewModel.Id),
                nameof(AutorViewModel.NomeCompleto),
                autorId);
        }

        // GET: Livro/Edit/5
        public override async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livroViewModel = await _livroAppService.GetByIdAsync(id.Value);
            if (livroViewModel == null)
            {
                return NotFound();
            }

            await PreencherSelect(livroViewModel.AutorId);

            return View(livroViewModel);
        }

        // POST: Livro/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, LivroViewModel livroViewModel)
        {
            if (!ModelState.IsValid)
            {
                await PreencherSelect(livroViewModel.AutorId);
            }

            return await base.Edit(id, livroViewModel);
        }

        [AcceptVerbs("GET", "POST")]
        public async Task<IActionResult> IsIsbnValid(string isbn, int id)
        {
            return await _livroAppService.IsIsbnValidAsync(isbn, id) 
                ? Json(true)
                : Json($"ISBN {isbn} já está sendo usado.");
        }

        protected override void ConfigureGridColumns(IGrid<LivroViewModel> grid)
        {
            grid.Columns.Add(model => model.Titulo);
            grid.Columns.Add(model => model.Isbn);
            grid.Columns.Add(model => model.Lancamento);
            grid.Columns.Add(model => model.QtdPaginas);
            grid.Columns.Add(model => model.Autor.NomeCompleto);
        }
    }
}

Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/mvc-grid/mvc-grid.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Presentation</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autor" asp-action="Index">Autor</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livro" asp-action="Index">Livro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" /> @*//Identity*@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/mvc-grid/mvc-grid.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>